CREATE DATABASE ICE_PROJECT;
USE ICE_PROJECT;

 -- KPI’s
-- 1.	MMBtu_TOTAL for Ethane & Ethanol 
SELECT FUEL_TYPE,SUM(MMBtu_TOTAL) AS MMBTU_TOTAL FROM ICE GROUP BY FUEL_TYPE HAVING FUEL_TYPE IN ("ETHANE","Ethanol");
-- 2.	Average GWht_TOTAL for 3M Company Facility
SELECT FACILITY_NAME,AVG(GWHT_TOTAL) AS AVG_GWHT_TOTAL FROM ICE GROUP BY FACILITY_NAME HAVING FACILITY_NAME="3M COMPANY";
-- 3.	Unit Name trend (1950-2020) Vs GWht_TOTAL
SELECT UNIT_NAME,SUM(GWHT_TOTAL) AS GWHT_TOTAL FROM ICE GROUP BY UNIT_NAME  ORDER BY GWHT_TOTAL DESC;
-- 4.	% Share of MMBtu_TOTAL & GWht_TOTAL for each MECS_Region
SELECT MECS_REGION, ROUND(SUM(MMBTU_TOTAL) / (SELECT SUM(MMBTU_TOTAL) FROM ICE) * 100, 2)  AS MMBTU_PERCENTAGE,
 ROUND(SUM(GWHT_TOTAL) / (SELECT SUM(GWHT_TOTAL) FROM ICE) * 100, 2)  AS GWHT_PERCENTAGE FROM ICE GROUP BY MECS_REGION;
-- 5.	PRIMARY_NAICS_TITLE Vs Facility Name and Fuel Type Stats
SELECT PRIMARY_NAICS_TITLE,FACILITY_NAME,FUEL_TYPE,SUM(MMBTU_TOTAL) AS MMBTU,SUM(GWHT_TOTAL) GWHT FROM ICE
GROUP BY PRIMARY_NAICS_TITLE,FACILITY_NAME,FUEL_TYPE ORDER BY  PRIMARY_NAICS_TITLE;
